// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

// Pishpirik uses per-room seat tokens, not Supabase auth sessions. Keep this
// middleware as a no-op so server functions never block on getSession().
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(async ({ next }) =>
  next(),
);
